# Toronto Neighborhoods Assignment (2)

### Heriberto Encinas LÃ³pez

## Getting Longitude and Latitude values

In this section we will get the longitude and latitude values for each postal code from our final dataset

In [1]:
#first we import the libraries we need
import pandas as pd
import requests
from bs4 import BeautifulSoup
import lxml

In [2]:
#first we load the given Geospatial_Coordinates.csv file
coord = pd.read_csv('Geospatial_Coordinates.csv')
coord.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [3]:
#now we load our dataset
pbndata = pd.read_csv('pbn_dataset.csv')
pbndata.head()

   Unnamed: 0 Postcode      Borough                           Neighbourhood
0           0      M1B  Scarborough                          Malvern, Rouge
1           1      M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2           2      M1E  Scarborough       Guildwood, West Hill, Morningside
3           3      M1G  Scarborough                                  Woburn
4           4      M1H  Scarborough                               Cedarbrae

In [4]:
#we create a dataframe that will contain all the data
df = pd.DataFrame(columns=['Postal Code','Borough','Neighbourhood','Latitude','Longitude'])
df.head()

Empty DataFrame
Columns: [Postal Code, Borough, Neighbourhood, Latitude, Longitude]
Index: []

In [5]:
#we insert the data
df['Postal Code'] = pbndata['Postcode']
df['Borough'] = pbndata['Borough']
df['Neighbourhood'] = pbndata['Neighbourhood']
df['Latitude'] = coord['Latitude']
df['Longitude'] = coord['Longitude']

df.head(30)

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, West Hill, Morningside",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park",43.727929,-79.262029
7,M1L,Scarborough,"Clairlea, Oakridge, Golden Mile",43.711112,-79.284577
8,M1M,Scarborough,"Scarborough Village West, Cliffside, Cliffcrest",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848
10,M1P,Scarborough,"Wexford Heights, Scarborough Town Centre, Dors...",43.757410,-79.273304
11,M1R,Scarborough,"Maryvale, Wexford",43.750072,-79.295849
12,M1S,Scarborough,Agincourt,43.794200,-79.262029
13,M1T,Scarborough,"Clarks Corners, Sullivan, Tam O'Shanter",43.781638,-79.304302
14,M1V,Scarborough,"Steeles East, L'Amoreaux East, Milliken, Aginc...",43.815252,-79.284577
15,M1W,Scarborough,L'Amoreaux West,43.799525,-79.318389
16,M1X,Scarborough,Upper Rouge,43.836125,-79.205636
17,M2H,North York,Hillcrest Village,43.803762,-79.363452
18,M2J,North York,"Fairview, Henry Farm, Oriole",43.778517,-79.346556
19,M2K,North York,Bayview Village,43.786947,-79.385975
20,M2L,North York,"York Mills, Silver Hills",43.757490,-79.374714
21,M2M,North York,"Willowdale, Newtonbrook",43.789053,-79.408493
22,M2N,North York,Willowdale South,43.770120,-79.408493
23,M2P,North York,York Mills West,43.752758,-79.400049
24,M2R,North York,Willowdale West,43.782736,-79.442259
25,M3A,North York,Parkwoods,43.753259,-79.329656
26,M3B,North York,Don Mills North,43.745906,-79.352188
27,M3C,North York,"Flemingdon Park, Don Mills South",43.725900,-79.340923
28,M3H,North York,"Bathurst Manor, Downsview North, Wilson Heights",43.754328,-79.442259
29,M3J,North York,"Northwood Park, York University",43.767980,-79.487262

In [6]:
#we save this dataset
df.to_csv('final_dataset.csv')